service: mathfever-api-v2

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stage: beta
  region: ap-southeast-2
  runtime: go1.x

functions:
  mathfeverApi:
    handler: bin/mathfeverApi
    memorySize: 128
    events:
      - http:
          path: /categories
          method: get
          cors: true
      - http:
          path: /calculation/{any}
          method: post
          cors: true
      - http:
          path: /{any+}
          method: post
          cors: true
