service: mathfever-api

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stage: beta
  region: ap-southeast-2
  runtime: go1.x

functions:
  categories:
    handler: bin/categories
    memorySize: 128
    events:
      - http:
          path: categories
          method: get
          cors: true
  # networking category
  binaryToDecimal:
    handler: bin/calculations/networking/binaryToDecimal
    memorySize: 128
    events:
      - http:
          path: calculation/binary-to-decimal
          method: post
          cors: true
  binaryToHexadecimal:
    handler: bin/calculations/networking/binaryToHexadecimal
    memorySize: 128
    events:
      - http:
          path: calculation/binary-to-hexadecimal
          method: post
          cors: true
  decimalToBinary:
    handler: bin/calculations/networking/decimalToBinary
    memorySize: 128
    events:
      - http:
          path: calculation/decimal-to-binary
          method: post
          cors: true
  decimalToHexadecimal:
    handler: bin/calculations/networking/decimalToHexadecimal
    memorySize: 128
    events:
      - http:
          path: calculation/decimal-to-hexadecimal
          method: post
          cors: true
  hexadecimalToBinary:
    handler: bin/calculations/networking/hexadecimalToBinary
    memorySize: 128
    events:
      - http:
          path: calculation/hexadecimal-to-binary
          method: post
          cors: true
  hexadecimalToDecimal:
    handler: bin/calculations/networking/hexadecimalToDecimal
    memorySize: 128
    events:
      - http:
          path: calculation/hexadecimal-to-decimal
          method: post
          cors: true
  # prime and numbers category
  isPrime:
    handler: bin/calculations/numbers/isPrime
    memorySize: 128
    events:
      - http:
          path: calculation/is-prime
          method: post
          cors: true
  highestCommonFactor:
    handler: bin/calculations/numbers/highestCommonFactor
    memorySize: 128
    events:
      - http:
          path: calculation/highest-common-factor
          method: post
          cors: true
  lowestCommonMultiple:
    handler: bin/calculations/numbers/lowestCommonMultiple
    memorySize: 128
    events:
      - http:
          path: calculation/lowest-common-multiple
          method: post
          cors: true
  # percentages category
  changeByPercentage:
    handler: bin/calculations/percentages/changeByPercentage
    memorySize: 128
    events:
      - http:
          path: calculation/change-number-by-percentage
          method: post
          cors: true
  numberFromPercentage:
    handler: bin/calculations/percentages/numberFromPercentage
    memorySize: 128
    events:
      - http:
          path: calculation/get-number-from-a-percentage
          method: post
          cors: true
  percentageChange:
    handler: bin/calculations/percentages/percentageChange
    memorySize: 128
    events:
      - http:
          path: calculation/find-percentage-difference-of-two-numbers
          method: post
          cors: true
  percentageFromNumber:
    handler: bin/calculations/percentages/percentageFromNumber
    memorySize: 128
    events:
      - http:
          path: calculation/find-percentages-of-a-number
          method: post
          cors: true
  # tsa category
  tsaPythagoreanTheorem:
    handler: bin/calculations/tsa/tsaPythagoreanTheorem
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-pythagorean-theorem
          method: post
          cors: true
  tsaCone:
    handler: bin/calculations/tsa/tsaCone
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-cone
          method: post
          cors: true
  tsaCube:
    handler: bin/calculations/tsa/tsaCube
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-cube
          method: post
          cors: true
  tsaCylinder:
    handler: bin/calculations/tsa/tsaCylinder
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-cylinder
          method: post
          cors: true
  tsaRectangularPrism:
    handler: bin/calculations/tsa/tsaRectangularPrism
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-rectangular-prism
          method: post
          cors: true
  tsaSphere:
    handler: bin/calculations/tsa/tsaSphere
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-sphere
          method: post
          cors: true
  tsaSquareBaseTriangle:
    handler: bin/calculations/tsa/tsaSquareBaseTriangle
    memorySize: 128
    events:
      - http:
          path: calculation/tsa-square-based-triangle
          method: post
          cors: true
